package:
   name: cudatoolkit
   version: {{ 11.0 }}

build:
  number: 999

test:
  requires:
    - numba
    - python
    - setuptools  # for pkg_resources
  commands:
    - test ! -f "${PREFIX}/lib/libaccinj64.so"         # [linux]
    - test ! -f "${PREFIX}/lib/libcuinj64.so"          # [linux]

about:
  description: Placeholder for CUDA Toolkit. This conda package does not install anything.
  summary: 'CUDA Toolkit Placeholder'
