{% set name = "pytorch" %}
{% set version = "1.8.0" %}
{% set wheel = "torch-1.8.0-cp36-cp36m-linux_aarch64.whl" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "../dist/{{ wheel }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ./{{ wheel }} -vv"

requirements:
  build:
    - conda-build
    - python
  host:
    - python
  run:
    - libopenblas
    - magma
    - numpy
    - python >=3.6,<3.7.0a0
    - typing_extensions

about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  summary: PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.
