{% set name = "pytorch" %}
{% set version = "1.7.1" %}
{% set wheel = "torch-1.7.1-cp36-cp36m-linux_aarch64.whl" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "../pytorch/dist/{{ wheel }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ./{{ wheel }} -vv"

requirements:
  build:
    - conda-build
    - python
  host:
    - python
  run:
    - openblas
    - magma
    - cudatoolkit ==10.2
    - numpy >=1.11
    - python >=3.7,<3.8.0a0
    - typing_extensions

about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  summary: PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.