{% set build = 0 %}
{% set version = '2.5.4' %}

package:
    name: magma
    version: {{version}}

about:
    home: http://icl.cs.utk.edu/magma/
    license: BSD
    summary: 'Matrix Algebra on GPU and Multicore Architectures'

source:
    fn: magma-{{version}}.tar.gz
    url: http://icl.cs.utk.edu/projectsfiles/magma/downloads/magma-{{version}}.tar.gz
    md5: 7f74217e2b668c038054008607fefc7d

requirements:
    build:
        - openblas

    run:
        - openblas

build:
    number: {{build}}
    string: cuda102_{{build}}