{% set build = 0 %}
{% set version = '2.5.4' %}

package:
    name: magma
    version: {{version}}

about:
    home: http://icl.cs.utk.edu/magma/
    license: BSD
    summary: 'Matrix Algebra on GPU and Multicore Architectures'

requirements:
    run:
        - libopenblas

build:
    number: {{build}}
    string: cuda102_{{build}}
    