{% set name = "torchtext" %}
{% set version = "0.8.1" %}
{% set wheel = "torchtext-0.8.1-cp36-cp36m-linux_aarch64.whl" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "../dist/{{ wheel }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ./{{ wheel }} -vv"

requirements:
  build:
    - conda-build
    - python
  host:
    - python
  run:
    - python
    - pytorch >=1.7.1
