{% set name = "grpcio" %}
{% set version = "1.34.0" %}
{% set wheel = "grpcio-1.34.0-cp36-cp36m-linux_aarch64.whl" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "../dist/{{ wheel }}"
  
build:
  number: 0
  script: "{{ PYTHON }} -m pip install ./{{ wheel }} -vv"
  
requirements:
  build:
    - conda-build
    - python
  host:
    - python
  run:
    - python
    - setuptools
    - six >=1.5.2
    - zlib
    - openssl

test:
  requires:
    - pip
  imports:
    - grpc
    - grpc._cython
    - grpc._cython._cygrpc
    - grpc.beta
    - grpc.framework
    - grpc.framework.common
    - grpc.framework.foundation
    - grpc.framework.interfaces
    - grpc.framework.interfaces.base
    - grpc.framework.interfaces.face
  commands:
    - python -m pip check

about:
  home: https://grpc.io
  license: Apache-2.0
  license_family: APACHE
  summary: HTTP/2-based RPC framework
  dev_url: https://pypi.org/project/grpcio/
