{% set name = "spacy" %}
{% set version = "2.3.5" %}
{% set wheel = "spacy-2.3.5-cp36-cp36m-linux_aarch64.whl" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "../dist/{{ wheel }}"
  
build:
  number: 0
  script: "{{ PYTHON }} -m pip install ./{{ wheel }} -vv"
  
requirements:
  build:
    - conda-build
    - python
  host:
    - python
  run:
    - catalogue >=0.0.7,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - cython-blis >=0.4.0,<0.8.0
    - importlib-metadata >=0.20
    - jsonschema
    - libgcc-ng >=7.5.0
    - libstdcxx-ng >=7.5.0
    - murmurhash >=0.28.0,<1.1.0
    - numpy >=1.16.5,<2.0a0
    - plac <1.0.0,>=0.9.6
    - preshed >=3.0.2,<3.1.0
    - python >=3.6,<3.8.0a0
    - requests >=2.13.0,<3.0.0
    - srsly >=1.0.2,<1.1.0
    - thinc >=7.4.1,<7.5.0
    - tqdm >=4.38.0,<5.0.0
    - wasabi >=0.4.0,<1.1.0

test:
  commands:
    - python -m pytest --tb=native --pyargs spacy
  imports:
    - spacy
  requires:
    - mock
    - pytest

about:
    description: 'spaCy is a library for advanced natural language processing in Python and Cython.'
    dev_url: https://github.com/explosion/spaCy
    doc_url: https://spacy.io
    home: https://spacy.io/
    license: MIT
    summary: Industrial-strength Natural Language Processing
